# Dockerfile: postgresql
# Kafouche PostgreSQL 16 Image.

FROM        ghcr.io/kafouche/alpine:latest

LABEL       org.opencontainers.image.authors="kafouche"
LABEL       org.opencontainers.image.base.name="ghcr.io/kafouche/postgres:16"
LABEL       org.opencontainers.image.ref.name="ghcr.io/kafouche/alpine"
LABEL       org.opencontainers.image.source="https://github.com/kafouche/container-postgres"
LABEL       org.opencontainers.image.title="PostgreSQL 16"

# ------------------------------------------------------------------------------

RUN         apk --no-cache --update upgrade \
            && apk --no-cache --update add \
              icu-data-full \
              postgresql16

RUN         install -d -g postgres -m 1775 -o postgres /run/postgresql

WORKDIR     /var/lib/postgresql/

USER        postgres

RUN         initdb \
              --data-checksums \
              --encoding UTF-8 \
              --icu-locale=en-001-x-icu \
              --locale-provider=icu \
              --pgdata /var/lib/postgresql/16/data

VOLUME      /var/lib/postgresql/

EXPOSE      5432/tcp

ENTRYPOINT  [ "/usr/bin/postgres" ]
CMD         [ "-D", "/var/lib/postgresql/16/data" ]